### ISSUE TITLE
KeyError: 'videoDetails' when trying to access video.title in a playlist

### ISSUE THREAD

**Issue by VisionsOfDrifting** [JuanBindez/pytubefix#101]
**Describe the bug**
Accessing video.title from a video in playlist.videos fails.

**To Reproduce**

Replace url with a public youtube playlist that has videos "https://www.youtube.com/playlist?list=*"

```
from pytubefix import YouTube, Playlist, Stream
from pytubefix.cli import on_progress

p: Playlist = Playlist(url)
for v in p.videos:
  print(v.title)
```

```
Traceback (most recent call last):
  File "/home/nick/Desktop/Python/youtube_parser/venv2/lib/python3.8/site-packages/pytubefix/__main__.py", line 547, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
...
  File "/home/nick/Desktop/Python/youtube_parser/app/download_playlist_audio.py", line 142, in <module>
    print(v.title)
  File "/home/nick/Desktop/Python/youtube_parser/venv2/lib/python3.8/site-packages/pytubefix/__main__.py", line 552, in title
    raise exceptions.PytubeFixError(
pytubefix.exceptions.PytubeFixError: Exception while accessing title of https://youtube.com/watch?v=MlwBZ2MSNtE. Please file a bug report at https://github.com/JuanBindez/pytubefix
```

**Expected behavior**
Access the video title without raising exception.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Python Version 3.8.10
 - Pytubefix Version 6.1.1

**Comment by VisionsOfDrifting** [comment]
@JuanBindez what version is your python? Maybe it is my version. I tried your example test and it didn't work either for any of these urls.

pytubefix_test.py
```
from pytubefix import YouTube
from pytubefix.cli import on_progress
 
# url = "https://www.youtube.com/watch?v=7NZ0fqliN-o"
# url = "https://www.youtube.com/watch?v=ZOXq2cWL99M"
url = "https://youtube.com/watch?v=MlwBZ2MSNtE"
 
yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
 
ys = yt.streams.get_highest_resolution()
ys.download()
```

```
~/Desktop/Python/youtube_parser$ python3 -m venv venv3
~/Desktop/Python/youtube_parser$ . venv3/bin/activate
(venv3) ~/Desktop/Python/youtube_parser$ pip install pytubefix
Collecting pytubefix
  Downloading pytubefix-6.1.2-py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 2.4 MB/s 
Installing collected packages: pytubefix
Successfully installed pytubefix-6.1.2
(venv3) ~/Desktop/Python/youtube_parser$ pip --version
pip 20.0.2 from /home/nick/Desktop/Python/youtube_parser/venv3/lib/python3.8/site-packages/pip (python 3.8)
(venv3) ~/Desktop/Python/youtube_parser$ python3 pytubefix_test.py 
Traceback (most recent call last):
  File "/home/nick/Desktop/Python/youtube_parser/venv3/lib/python3.8/site-packages/pytubefix/__main__.py", line 547, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pytubefix_test.py", line 8, in <module>
    print(yt.title)
  File "/home/nick/Desktop/Python/youtube_parser/venv3/lib/python3.8/site-packages/pytubefix/__main__.py", line 552, in title
    raise exceptions.PytubeFixError(
pytubefix.exceptions.PytubeFixError: Exception while accessing title of https://youtube.com/watch?v=ZOXq2cWL99M. Please file a bug report at https://github.com/JuanBindez/pytubefix
```

**Comment by VisionsOfDrifting** [comment]
I found the issue in the debugger. I had my VPN on and in [YouTube.check_availablity() ](https://github.com/JuanBindez/pytubefix/blob/main/pytubefix/__main__.py#L260)
```
status, messages = extract.playability_status(self.watch_html)
```

status = 'LOGIN_REQUIRED'
messages = ['Sign in to confirm you’re not a bot']

When I try with my VPN off it works fine. Thanks for fixing this library!
