### ISSUE TITLE
KeyError: 'streamingData'

### ISSUE THREAD

**Issue by GordonQuick** [JuanBindez/pytubefix#105]
**Describe the bug**
KeyError: 'streamingData' when trying to download a playlist.

**To Reproduce**
* Trying to download playlist (https://www.youtube.com/playlist?list=PLmZJ1ohwjt2O6qMwMFCRJMR_SnwyKFfvL) 
* Some videos get downloaded but error after some videos

**Expected behavior**
downloading of all videos in the playlist

**Error log**
The ANDROID_TESTSUITE client did not get a valid response, trying to use the WEB client.
Video ID: KU5oMbX7m38
Please open an issue at https://github.com/JuanBindez/pytubefix/issues and provide this log output.
Traceback (most recent call last):
  File "c:\Users\Gord\Python\playlistdownloader.py", line 7, in <module>
    video.streams.first().download(r'G:\test2')
    ^^^^^^^^^^^^^
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 498, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 226, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 211, in streaming_data
    return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'

**Comment by GordonQuick** [comment]
Error is fixed. However, Download of age restricted videos is still not possible. Even with login via oauth it fails.

```
Traceback (most recent call last):
  File "c:\Users\Gord\Python\playlistdownloader.py", line 10, in <module>
    video.streams.first().download(r'G:\test')
    ^^^^^^^^^^^^^
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 501, in streams
    self.check_availability()
  File "C:\Users\Gord\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytubefix\__main__.py", line 282, in check_availability
    raise exceptions.AgeRestrictedError(video_id=self.video_id)
pytubefix.exceptions.AgeRestrictedError: Video ID = KU5oMbX7m38: is age restricted, and can't be accessed without logging in.
```
