### ISSUE TITLE
Channel length throwing exception

### ISSUE THREAD

**Issue by awesome-bhatti** [JuanBindez/pytubefix#132]
**Describe the bug**
I noticed getting channel length is throwing exception. it seems to be a KeyError. 

````
Traceback (most recent call last):
  File "/Users/xxxx/Documents/xxxx/test.py", line 49, in <module>
    print(c.length)
          ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytubefix/contrib/channel.py", line 467, in length
    return self.initial_data['header']['c4TabbedHeaderRenderer']['videosCountText']['runs'][0]['text']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'c4TabbedHeaderRenderer'

````

**To Reproduce**
````
c = Channel('https://www.youtube.com/channel/UCNJ1Ymd5yFuUPtn21xtRbbw')
print(c.length)
````

**Expected behavior**
it should return the number of videos of the channel
channel.length can have this implementation as one of the options.
This will return 4.4k if there are 4400 videos and so on. 
it will return a string.  

````
for metadata_row in self.initial_data["header"]["pageHeaderRenderer"]["content"]["pageHeaderViewModel"]["metadata"]["contentMetadataViewModel"]["metadataRows"]:
    for metadata_part in metadata_row["metadataParts"]:
        if "text" in metadata_part and "content" in metadata_part["text"]:
            if str(metadata_part["text"]["content"]).endswith("videos"):
                return str(metadata_part["text"]["content"]).split(" videos")[0]

````

**Desktop (please complete the following information):**
 - OS: [Your Operating System and Version]: macOS 2019
 - Python Version [x.y.z]: 3.11.6
 - Pytubefix Version [x.y.z]: 6.5.1

**Additional context**

**Comment by awesome-bhatti** [comment]
One observation. 
We can still get the number of videos by iterating over video_urls and keeping track of length.
But that only gives the video count and does not include shorts count or live stream count I think. 

If we implement above suggested method, we will get complete count.
