### ISSUE TITLE
 extract.apply_signature and RegexMatchError

### ISSUE THREAD

**Issue by CarrotTea** [JuanBindez/pytubefix#232]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
Getting the following error:
```
Traceback (most recent call last):
  File "C:\Users\carol\PycharmProjects\PyProPract\.venv\Lib\site-packages\pytubefix\__main__.py", line 253, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\carol\PycharmProjects\PyProPract\.venv\Lib\site-packages\pytubefix\extract.py", line 425, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\carol\PycharmProjects\PyProPract\.venv\Lib\site-packages\pytubefix\cipher.py", line 25, in __init__
    self.throttling_function_name = get_throttling_function_name(js)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\PycharmProjects\PyProPract\.venv\Lib\site-packages\pytubefix\cipher.py", line 137, in get_throttling_function_name
    raise RegexMatchError(
pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\carol\PycharmProjects\PyProPract\pyfix.py", line 9, in <module>
    ys = yt.streams.get_highest_resolution()
         ^^^^^^^^^^
  File "C:\Users\carol\PycharmProjects\PyProPract\.venv\Lib\site-packages\pytubefix\__main__.py", line 546, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\carol\PycharmProjects\PyProPract\.venv\Lib\site-packages\pytubefix\__main__.py", line 260, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\carol\PycharmProjects\PyProPract\.venv\Lib\site-packages\pytubefix\extract.py", line 425, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\carol\PycharmProjects\PyProPract\.venv\Lib\site-packages\pytubefix\cipher.py", line 25, in __init__
    self.throttling_function_name = get_throttling_function_name(js)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\PycharmProjects\PyProPract\.venv\Lib\site-packages\pytubefix\cipher.py", line 137, in get_throttling_function_name
    raise RegexMatchError(
pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
```

__________
**code that was used that resulted in the bug**

``

```
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = input("URL >")

yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)

ys = yt.streams.get_highest_resolution()
ys.download()

```

__________
**Expected behavior**
I used this about a month ago to download some videos, but I've been getting an error.

__________
**Screenshots**

__________
**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Python Version 3.12.6
 - Pytubefix Version 6.16.2

__________
**Additional context**

**Comment by felipeucelli** [comment]
Please check the version of pytubefix you are using, this error log appears to be out of date.

**Comment by CarrotTea** [comment]
> Please check the version of pytubefix you are using, this error log appears to be out of date.

I was scratching my head over this because I'd updated my Python version, my pytubefix version, etc. But I forgot to update it on pycharm lol. Thank you for your help, this helped me crack the case 🙏🏻
