### ISSUE TITLE
can't download video

### ISSUE THREAD

**Issue by pympk** [JuanBindez/pytubefix#252]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
This is the error message

VideoUnavailable                          Traceback (most recent call last)
Cell In[7], line 9
      6 yt = YouTube(url, on_progress_callback = on_progress)
      7 print(yt.title)
----> 9 ys = yt.streams.get_highest_resolution()
     10 ys.download()

File c:\Users\john\Files_win10\python\py310\.venv\lib\site-packages\pytubefix\__main__.py:629, in YouTube.streams(self)
    623 @property
    624 def streams(self) -> StreamQuery:
    625     """Interface to query both adaptive (DASH) and progressive streams.
    626 
    627     :rtype: :class:`StreamQuery <StreamQuery>`.
    628     """
--> 629     self.check_availability()
    630     return StreamQuery(self.fmt_streams)

File c:\Users\john\Files_win10\python\py310\.venv\lib\site-packages\pytubefix\__main__.py:335, in YouTube.check_availability(self)
    333         raise exceptions.VideoRegionBlocked(video_id=self.video_id)
    334     else:
--> 335         raise exceptions.VideoUnavailable(video_id=self.video_id)
    337 elif status == 'LOGIN_REQUIRED':
    338     if reason == (
    339             'Sign in to confirm your age'
    340     ):

VideoUnavailable: xy4PRGtr61w is unavailable

__________
**code that was used that resulted in the bug**

```python
from pytubefix import YouTube
from pytubefix.cli import on_progress
 
url = "https://youtu.be/xy4PRGtr61w"
 
yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
 
ys = yt.streams.get_highest_resolution()
ys.download()

```

__________
**Expected behavior**
Code executed without error

__________
**Screenshots**

__________
**Desktop (please complete the following information):**
 - OS: windows 10
 - Python Version [x.y.z] 3.10.5
 - Pytubefix Version [x.y.z] 6.17.0
 - using vscode jupyter notebook

__________
**Additional context**

**Comment by NannoSilver** [comment]
Upgrade to latest pytubefix version

**Comment by JuanBindez** [comment]
try: pytubefix==7.1rc1

**Comment by victorfriedrich** [comment]
Same issue running the above code with pytubefix==7.1rc1

```
Elite Japanese Running Drills  洛南高校陸上部ランニングドリル動きづくり
Traceback (most recent call last):
  File "/Users/victorfriedrich/lang/backend/pytube.py", line 9, in <module>
    ys = yt.streams.get_highest_resolution()
         ^^^^^^^^^^
  File "/Users/victorfriedrich/lang/backend/pytubefix/__main__.py", line 563, in streams
    self.check_availability()
  File "/Users/victorfriedrich/lang/backend/pytubefix/__main__.py", line 305, in check_availability
    raise exceptions.VideoUnavailable(video_id=self.video_id)
pytubefix.exceptions.VideoUnavailable: xy4PRGtr61w is unavailable
```

**Comment by paichiwo** [comment]
same issue on my end

**Comment by jaferrando** [comment]
Applied the changes in 7.1rc1 but actually had to go all the way and pass in this line instead of raising exception, and then it worked for me.

https://github.com/felipeucelli/pytubefix/blob/54dec63593a5bd0e8da2ca80c2ca604f643fcbec/pytubefix/__main__.py#L373

**Comment by limFakson** [comment]
Same issue here

    raise exceptions.VideoUnavailable(video_id=self.video_id)
pytubefix.exceptions.VideoUnavailable: QrGInk-S8F4 is unavailable

**Comment by victorfriedrich** [comment]
Could resolve the problem by following the solution from another issue:

> YouTube appears to be blocking some requests made by the `ANDROID_TESTSUITE` client.
> 
> Try another client, for example `IOS`, `WEB_EMBED` , `MWEB` or `WEB_CREATOR`, and tell us the result:
> 
> ```python
> yt = YouTube(video_url, 'WEB_CREATOR')
> ```

_Originally posted by @felipeucelli in https://github.com/JuanBindez/pytubefix/issues/242#issuecomment-2366911626_

**Comment by limFakson** [comment]
> ```python
> WEB_CREATOR
> ```

It's working now thanks

**Comment by pympk** [comment]
This is my first bug report. I'm amazed how fast the community found a solution. Thank you.
