### ISSUE TITLE
Playlist Obj difficulties with .last_updated attribute

### ISSUE THREAD

**Issue by wyattZarkLab** [JuanBindez/pytubefix#307]
**:exclamation:  DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE :exclamation:**

lack of information will lead to closure of the issue

__________
**Describe the bug**
Playlist Object .last_updated attribute attempts to access .sidebar_info array, throws index error on 0.  Directly calling playlistObj.sidebar_info[0] does not throw error. 

__________
**code that was used that resulted in the bug**

```python
>>> from pytubefix import Playlist
>>> a = Playlist('https://www.youtube.com/playlist?list=PLWOf5LXf8YNW6Xf6w4CT4KZ8lWU1nH9rz')
>>> a.last_updated
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pytubefix/contrib/playlist.py", line 383, in last_updated
    last_updated_text = self.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer'][
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
>>> a.sidebar_info # no issue
>>> b = a.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer']
>>> b = a.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer']['stats'][2]['runs'][1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>> b = a.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer']['stats'][2]['runs'][0]
'Updated today'
>>> 

```

__________
**Expected behavior**

Use of Playlist Object `.last_updated` returns string or datetime value.
__________
**Screenshots**

__________
**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.7.6
 - Python Version 3.11.8
 - Pytubefix Version 8.20

__________
**Additional context**

**Comment by SteveRadich** [comment]
FYI: Description has similar issues sometimes, just adding it for when someone debugs maybe check for that also but I don't think it's a distinct issue - The times I saw last_updated errors I often had description errors also.
