### ISSUE TITLE
pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js

### ISSUE THREAD

**Issue by akirapix** [JuanBindez/pytubefix#375]
Hi,

more or less 12 hours ago a new error occurred.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pytubefix/__main__.py", line 287, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js, self.js_url)
  File "/usr/local/lib/python3.9/site-packages/pytubefix/extract.py", line 455, in apply_signature
    cipher = Cipher(js=js, js_url=url_js)
  File "/usr/local/lib/python3.9/site-packages/pytubefix/cipher.py", line 25, in __init__
    self.throttling_function_name = get_throttling_function_name(js, js_url)
  File "/usr/local/lib/python3.9/site-packages/pytubefix/cipher.py", line 179, in get_throttling_function_name
    raise RegexMatchError(
pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js
```

to reproduce this error i used this code:

```
from pytubefix import YouTube
import json 
import datetime
import sys

try:

	yt = YouTube(
		"https://www.youtube.com/watch?v=VXWE83j3-ro"
		, allow_oauth_cache=True
		, use_oauth=True
	)

	stream = yt.streams.filter(only_audio=True).order_by('abr').desc().first()

	print(json.dumps({
		'title': yt.title,
		'thumbnail': yt.thumbnail_url
	}))
	
except:
	type, value, traceback = sys.exc_info()
	print('Error opening %s: %s' % (value.filename, value.strerror))

```

the expected behaviour would have been to print a video's title and thumbnail

- **Operating System:** OSX 12.7.6 and Linux 
- **Python Version:** 3.9.17
- **Pytubefix Version:** 8.8.0

**Comment by direct-dok** [comment]
Hello everyone. I have the same problem, has someone already found a solution?

**Comment by asil004** [comment]
same

**Comment by felipeucelli** [comment]
Hello, try this: #374

**Comment by Pa3kx** [comment]
@felipeucelli I cloned the the repo. got all branches. checkedout into dev and pip installed that
git clone https://github.com/JuanBindez/pytubefix.git
git fetch --all
git checkout dev
then cd pytubefix
pip install .

It works. Thanks legends! 🎩

**Comment by JuanBindez** [comment]
only pip install pytubefix --upgrade

**Comment by Yukimx** [comment]
I tried pytubefix 8.8.0 and 8.8.1 and still get this error

**Comment by akirapix** [comment]
i tried 8.8.1 an worked. from my point of view issue can be closed
