### ISSUE TITLE
Failure to download a Video with a Title including '//', on a Mac

### ISSUE THREAD

**Issue by gthbscks01** [JuanBindez/pytubefix#376]
# 🛑 DO NOT REMOVE OR SKIP THIS ISSUE TEMPLATE 🛑  
Issues with incomplete or missing information will be **closed automatically**.

---

## 🐞 **Bug Description**  
Provide a clear and concise description of the bug.  

---

## 🔢 **Code Snippet**  
Include the minimal code snippet that reproduces the issue.  

```python
from pytubefix import YouTube

# Insert your code here
```

---

## 🎯 **Expected Behavior**  
Describe what you expected to happen instead of the observed behavior.  

---

## 📸 **Screenshots or Logs**  
If applicable, attach screenshots or logs that demonstrate the issue.  
(Use a service like [Pastebin](https://pastebin.com/) if the logs are too lengthy.)  

---

## 🖥️ **Environment Details**  
Fill in the details below about your setup:  
- **Operating System:** [e.g., Windows 10, macOS Monterey]  
- **Python Version:** [e.g., 3.9.7]  
- **Pytubefix Version:** [e.g., 1.2.3]  

---

## 📋 **Additional Context**  
Add any additional information or context that might help us resolve the issue.  

---

### ✅ **Checklist Before Submitting**  
- [x] I have read the [contribution guidelines](https://github.com/JuanBindez/pytubefix/blob/main/Contributing.md).  
- [x] I have verified that the issue exists in the latest version of the library.  
- [x] I have included all necessary details to reproduce the bug.  

---

### 🚀 **Next Steps**  
Once submitted, we will triage the issue. Make sure to respond to follow-up questions to keep the process smooth.

**Comment by gthbscks01** [comment]
On a 2017 iMac, running MacOS  10.13.6, and various latest Versions of Python, 3.10.11 3.11.9 3.12.8, and 3.13.1.

The Code used:

from pytubefix import YouTube
from pytubefix.cli import on_progress
import subprocess

# -------------------------------------------------------------------------------------
def Read_From_Clipboard():
 return subprocess.check_output('pbpaste', env={'LANG': 'en_US.UTF-8'}).decode('utf-8')
# -------------------------------------------------------------------------------------

url = Read_From_Clipboard()
if(not('youtube' in url)) : print('Not a YouTube URL'); exit()

yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
 
ys = yt.streams.get_highest_resolution()
ys.download()

... using this YouTube Link: https://www.youtube.com/watch?v=enuOArEfqGo, Titled: The Good, the Bad and the Ugly - The Danish National Symphony Orchestra (Live), the File is properly downloaded.

... using this YouTube Link: https://www.youtube.com/watch?v=DT1NJwEi6nw, Titled: For A Few Dollars More // The Danish National Symphony Orchestra (Live), the  Code fails, with the following Message:

Traceback (most recent call last):
  File "/Users/s/Desktop/*Programming_Utilities/YouTube_Videos-Downloader.01.py", line 25, in <module>
    ys.download()
    ~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pytubefix/streams.py", line 369, in download
    with open(file_path, "wb") as fh:
         ~~~~^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/s/For A Few Dollars More / The Danish National Symphony Orchestra (Live).mp4'

Somehow, the '//' in the Title is the cause of the Failure.
