### ISSUE TITLE
JavaScript interpretation error when downloading videos with pytubefix

### ISSUE THREAD

**Issue by deeffest** [JuanBindez/pytubefix#383]
# 🛑 DO NOT REMOVE OR SKIP THIS ISSUE TEMPLATE 🛑  
Issues with incomplete or missing information will be **closed automatically**.

---

## 🐞 **Bug Description**  
When attempting to download any video, an error occurs related to JavaScript interpretation.

---

## 🔢 **Code Snippet**  
Include the minimal code snippet that reproduces the issue.  

```python
from pytubefix import YouTube

yt = YouTube(
    "https://youtube.com/watch?v=dQw4w9WgXcQ",
    use_oauth=True,
    allow_oauth_cache=True
)
stream = yt.streams.get_highest_resolution()
stream.download()
```

---

## 🎯 **Expected Behavior**  
The code should successfully download the specified video without errors.

---

## 📸 **Screenshots or Logs**  
```
Traceback (most recent call last):
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 556, in _index
    return obj[int(idx)] if isinstance(obj, list) else obj[idx]
                                                       ~~~^^^^^
KeyError: 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Program Files\Projects\TESTS #1\test.py", line 8, in <module>
    stream = yt.streams.get_audio_only()
             ^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\__main__.py", line 637, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\__main__.py", line 287, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js, self.js_url)
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\extract.py", line 486, in apply_signature
    signature = cipher.get_signature(ciphered_signature=stream["s"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\cipher.py", line 50, in get_signature
    return self.js_interpreter.call_function(self.signature_function_name, ciphered_signature)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 1096, in call_function
    return self.extract_function(funcname)(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 261, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 1106, in resf
    ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 671, in interpret_statement
    cndn = _js_ternary(self.interpret_expression(cndn, local_vars, allow_recursion))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 1029, in interpret_expression
    ret, should_return = self.interpret_statement(expr, local_vars, allow_recursion)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 1013, in interpret_statement
    return eval_method(), should_return
           ^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 904, in eval_method
    return self._index(obj, member, nullish)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 560, in _index
    raise self.Exception(f'Cannot get index {idx}', repr(obj), cause=e)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pytubefix\jsinterp.py", line 463, in __init__
    super().__init__(msg, *args, **kwargs)
TypeError: Exception() takes no keyword arguments
```

---

## 🖥️ **Environment Details**  
Fill in the details below about your setup:  
- **Operating System:** [Windows 10 22H2]  
- **Python Version:** [3.12.3]  
- **Pytubefix Version:** [8.8.1]  

---

## 📋 **Additional Context**  
The problem happens with any download method, whether it’s `get_highest_resolution()` or `get_audio_only()`. I’ve tried updating the library and clearing the OAuth cache, but nothing seems to fix it.

---
### 🚀 **Next Steps**  
Once submitted, we will triage the issue. Make sure to respond to follow-up questions to keep the process smooth.

**Comment by sb0y** [comment]
Same issue here

```python
warp_beacon  | 2024-12-17 10:22:23,822 - root - ERROR - Exception() takes no keyword arguments
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 556, in _index
warp_beacon  |     return obj[int(idx)] if isinstance(obj, list) else obj[idx]
warp_beacon  | KeyError: 'py'
warp_beacon  |
warp_beacon  | During handling of the above exception, another exception occurred:
warp_beacon  |
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/__init__.py", line 134, in do_work
warp_beacon  |     items = actor.download(job.url)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/youtube/music.py", line 50, in download
warp_beacon  |     return self._download_hndlr(self._download, url)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/youtube/abstract.py", line 193, in _download_hndlr
warp_beacon  |     ret_val = func(*args, **kwargs)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/youtube/music.py", line 21, in _download
warp_beacon  |     stream = yt.streams.get_audio_only()
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/__main__.py", line 637, in streams
warp_beacon  |     return StreamQuery(self.fmt_streams)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/__main__.py", line 287, in fmt_streams
warp_beacon  |     extract.apply_signature(stream_manifest, self.vid_info, self.js, self.js_url)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/extract.py", line 486, in apply_signature
warp_beacon  |     signature = cipher.get_signature(ciphered_signature=stream["s"])
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/cipher.py", line 50, in get_signature
warp_beacon  |     return self.js_interpreter.call_function(self.signature_function_name, ciphered_signature)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 1096, in call_function
warp_beacon  |     return self.extract_function(funcname)(args)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 261, in __call__
warp_beacon  |     return self.func(*args, **kwargs)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 1106, in resf
warp_beacon  |     ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 671, in interpret_statement
warp_beacon  |     cndn = _js_ternary(self.interpret_expression(cndn, local_vars, allow_recursion))
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 1029, in interpret_expression
warp_beacon  |     ret, should_return = self.interpret_statement(expr, local_vars, allow_recursion)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 1013, in interpret_statement
warp_beacon  |     return eval_method(), should_return
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 904, in eval_method
warp_beacon  |     return self._index(obj, member, nullish)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 560, in _index
warp_beacon  |     raise self.Exception(f'Cannot get index {idx}', repr(obj), cause=e)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pytubefix/jsinterp.py", line 463, in __init__
warp_beacon  |     super().__init__(msg, *args, **kwargs)
warp_beacon  | TypeError: Exception() takes no keyword arguments
```

Example links
https://music.youtube.com/watch?v=BlaWhtHmUw4&si=7ARZeu9Un3GvVx7Z
https://www.youtube.com/watch?v=tRwHpyOq4P4&feature=youtu.be

**Comment by JuanBindez** [comment]
try v8.8.2

**Comment by deeffest** [comment]
Yes, 8.8.2 solved that problem.

**Comment by sb0y** [comment]
Confirmed, issue solved
