### ISSUE TITLE
Get stream don't work with a specific url

### ISSUE THREAD

**Issue by gonzo-oin** [JuanBindez/pytubefix#385]
## 🐞 **Bug Description**  
get_highest_resolution don't work with a specific url.
`https://www.youtube.com/watch?v=2rWXguw0S-k`

I get a `VideoUnavailable` error

---

## 🔢 **Code Snippet**  

```python
from pytubefix import YouTube

url="https://www.youtube.com/watch?v=2rWXguw0S-k"
    try:
        yt = YouTube(url)
        stream_video = yt.streams.get_highest_resolution()
        return redirect(stream_video.url)
    except Exception as e:
        print(f"Error {e}")
        abort(422, "Invalid URL.")
```
---

## 🎯 **Expected Behavior**  

It should redirect to the video stream url.
As it work for "https://www.youtube.com/watch?v=9ix7TUGVYIo" 

---

## 🖥️ **Environment Details**  
Fill in the details below about your setup:  
- **Operating System:**  macOS Monterey
- **Python Version:** 3.10
- **Pytubefix Version:** 9.8.2

---

**Comment by brumitz** [comment]
# 🐞 Bug Description:
Hi, I'am facing the same error: VideoUnavailable: U-DAVNAyD88 is unavailable

## complete Traceback:
Benjamin Blümchen - wird reich (Folge 53) | ZWEITPLATZIERTE Hörspiel des Monats JUNI
2792
Benjamin Blümchen TV
U-DAVNAyD88
Traceback (most recent call last):
  File "/Users/moritz/dev_code/projects/yt_downloader/yt_audio.py", line 13, in <module>
    print(yt.streams)
          ^^^^^^^^^^
  File "/Users/moritz/dev_code/venv_media/lib/python3.13/site-packages/pytubefix/__main__.py", line 636, in streams
    self.check_availability()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/moritz/dev_code/venv_media/lib/python3.13/site-packages/pytubefix/__main__.py", line 343, in check_availability
    raise exceptions.VideoUnavailable(video_id=self.video_id)
pytubefix.exceptions.VideoUnavailable: U-DAVNAyD88 is unavailable

# 🔢 Code Snippet:
```
import os
from pytubefix import YouTube
from pytubefix.cli import on_progress

#Input zur Eingabe der gewünschten URL
url = 'https://www.youtube.com/watch?v=U-DAVNAyD88'

yt = YouTube(url, on_progress_callback=on_progress)
print(yt.title)
print(yt.length)
print(yt.author)
print(yt.video_id)
print(yt.streams)

ys = yt.streams.get_audio_only()
ys.download()
```

# 🎯 Expected Behavior:
Should print the available streams and then download the audio file. Like in this example:

```
import os
from pytubefix import YouTube
from pytubefix.cli import on_progress

#Input zur Eingabe der gewünschten URL
url = 'https://www.youtube.com/watch?v=_01F5mi5btM&t=4s'

yt = YouTube(url, on_progress_callback=on_progress)
print(yt.title)
print(yt.length)
print(yt.author)
print(yt.video_id)
print(yt.streams)

ys = yt.streams.get_audio_only()
ys.download()
```

## Output console:
Bibi Blocksberg - Urlaub am See (Folge 138) | SOMMER SPEZIAL | Hörspiel in voller Länge
2892
Bibi Blocksberg TV
_01F5mi5btM
[<Stream: itag="18" mime_type="video/mp4" res="360p" fps="25fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">, <Stream: itag="136" mime_type="video/mp4" res="720p" fps="25fps" vcodec="avc1.4d401f" progressive="False" type="video">, <Stream: itag="247" mime_type="video/webm" res="720p" fps="25fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="398" mime_type="video/mp4" res="720p" fps="25fps" vcodec="av01.0.05M.08" progressive="False" type="video">, <Stream: itag="135" mime_type="video/mp4" res="480p" fps="25fps" vcodec="avc1.4d401e" progressive="False" type="video">, <Stream: itag="244" mime_type="video/webm" res="480p" fps="25fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="397" mime_type="video/mp4" res="480p" fps="25fps" vcodec="av01.0.04M.08" progressive="False" type="video">, <Stream: itag="134" mime_type="video/mp4" res="360p" fps="25fps" vcodec="avc1.4d401e" progressive="False" type="video">, <Stream: itag="243" mime_type="video/webm" res="360p" fps="25fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="396" mime_type="video/mp4" res="360p" fps="25fps" vcodec="av01.0.01M.08" progressive="False" type="video">, <Stream: itag="133" mime_type="video/mp4" res="240p" fps="25fps" vcodec="avc1.4d4015" progressive="False" type="video">, <Stream: itag="242" mime_type="video/webm" res="240p" fps="25fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="395" mime_type="video/mp4" res="240p" fps="25fps" vcodec="av01.0.00M.08" progressive="False" type="video">, <Stream: itag="160" mime_type="video/mp4" res="144p" fps="25fps" vcodec="avc1.4d400c" progressive="False" type="video">, <Stream: itag="278" mime_type="video/webm" res="144p" fps="25fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="394" mime_type="video/mp4" res="144p" fps="25fps" vcodec="av01.0.00M.08" progressive="False" type="video">, <Stream: itag="139" mime_type="audio/mp4" abr="48kbps" acodec="mp4a.40.5" progressive="False" type="audio">, <Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2" progressive="False" type="audio">, <Stream: itag="249" mime_type="audio/webm" abr="50kbps" acodec="opus" progressive="False" type="audio">, <Stream: itag="250" mime_type="audio/webm" abr="70kbps" acodec="opus" progressive="False" type="audio">, <Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus" progressive="False" type="audio">]

# 🖥️ Environment Details

Fill in the details below about your setup:

Operating System: macOS Sonoma
Python Version: 3.13.1
Pytubefix Version: 8.8.5

Hope someone can help. Thank you.

**Comment by stephane-alma-mwm** [comment]
The issue is fixed with 8.10.1 🥳

**Comment by gonzo-oin** [comment]
The issue is fixed in version 8.10.1 🥳

**Comment by brumitz** [comment]
Works for may case too!  Thank you! 🥳
